name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - name: Clone pymol
        run: |
          git clone https://github.com/schrodinger/pymol-open-source.git
          git clone https://github.com/rcsb/mmtf-cpp.git
          mv mmtf-cpp/include/mmtf* pymol-open-source/include/
          rm -rf mmtf-cpp
          mv pymol-open-source/* .
          rm -rf pymol-open-source

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD: cp38-macosx_x86_64 cp38-manylinux_x86_64
          CIBW_BUILD_VERBOSITY: 0
          CIBW_BEFORE_BUILD_MACOS: brew install catch2 freeglut freetype glew glm libpng libxml2 msgpack msgpack-cxx netcdf sip
          CIBW_BEFORE_BUILD_LINUX: yum install -y gcc gcc-c++ kernel-devel freeglut-devel glew-devel libpng-devel freetype-devel msgpack-devel libxml2-devel glm-devel netcdf-devel
          CIBW_ENVIRONMENT_MACOS: CPPFLAGS="-I/usr/local/opt/freetype2/include/freetype2"

      - run: ls -l wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
