name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Clone pymol
        run: |
          git clone https://github.com/schrodinger/pymol-open-source.git
          git clone https://github.com/rcsb/mmtf-cpp.git
          mv mmtf-cpp/include/mmtf* pymol-open-source/include/
          rm -rf mmtf-cpp
          mv pymol-open-source/* .
          rm -rf pymol-open-source

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: pp* *musllinux*
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_BUILD_MACOS: brew install catch2 freeglut freetype glew glm libpng libxml2 msgpack msgpack-cxx netcdf sip
          CIBW_BEFORE_BUILD_LINUX: dnf install -y epel-release && dnf install -y gcc gcc-c++ kernel-devel freeglut-devel glew-devel libpng-devel freetype-devel msgpack-devel libxml2-devel glm-devel netcdf-devel
          CIBW_ENVIRONMENT_MACOS: CPPFLAGS="-I/usr/local/opt/freetype2/include/freetype2"

      - run: ls -l wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Deployment
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl
